### ISSUE TITLE
Communities at bottom of pages doesn't have a link.

### ISSUE THREAD

**Issue by craigfisk** [Marmalade-ai/company-website#137]
Maybe the best thing is to delete it (or comment it out, so we remember to do something with it)?

**Comment by jimtyhurst** [comment]
@craigfisk : Please check this again, because I cannot reproduce this error.

* I tested the deployment at https://marmaladeai.gatsbyjs.io/ using several browsers:
    * macOS: Chrome, Firefox, Brave
    * iPhone: Chrome, Firefox
* Looking at the [code](./src/components/layout/Footer.js), I can see that the link is there:
    ```javascript
    <Link to="/communities">Communities</Link>
    ```
* We use the `Link` element, because `Communities` is a page on this site.

**Comment by jimtyhurst** [comment]
@craigfisk and @jimtyhurst agree that current behavior is correct.
