### ISSUE TITLE
Code showing in Forum header

### ISSUE THREAD

**Issue by jimtyhurst** [Marmalade-ai/company-website#169]
* Some formatting code is being displayed on Forum pages:
    ```
    #top-navbar { margin-right: auto; margin-left: auto; margin-top: 10px; max-width: 1110px; //You can move the menu to the left, to the center or to the right text-align: center; } { background-color: red; }
    ```
* This occurs on the login page and within the forum after you login.
* See attached screenshots.

## Environments where observed
* macOS 11.6
* Latest Chrome: Version 93.0.4577.82 (Official Build) (x86_64)
* Latest Firefox: 92.0.1 (64-bit)
* Latest Safari: Version 15.0 (16612.1.29.41.4, 1661
![Code-showing-on-Forum-login-page](https://user-images.githubusercontent.com/346287/135698542-4f52a975-40ef-4eff-bc67-9562665ec9da.png)
![Code-showing-on-Forum-page](https://user-images.githubusercontent.com/346287/135698545-7559db10-5230-4fe6-a665-ced1590cac08.png)
2)

**Comment by craigfisk** [comment]
You're right. I see that same CSS styling code for forum.marmalade.ai, too.
OK, will work on figuring it out.

https://www.linkedin.com/in/craigfisk <https://about.me/craigfisk>
(650) 336-8770

**Comment by craigfisk** [comment]
Okay, the code at the top of the page when you go to forum.marmalade.ai should be gone now. So: FIXED.
My suspicion was right -- it was stray code in the "After Header" section when you edit CSS/HTML for the "Light" theme, which is why it wasn't showing up on the dark theme. It would be good to also get the networking_banner in here at the same time, but haven't quite gotten that working.

**Comment by jimtyhurst** [comment]
I confirmed the fix on Chrome on macOS with Light theme.
